services:
  database:
    container_name: bonusx-db
    image: postgres:16.1-alpine
    environment:
      TZ: Europe/Moscow
      LANG: ru_RU.UTF-8
      LC_COLLATE: ru_RU.UTF-8
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256'
    ports:
      - 5432:5432
    networks:
      - bonusx-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    container_name: bonusx-api
    image: bonusx-api
    environment:
      TZ: "Europe/Moscow"
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      KNEX_DEBUG: true
    build:
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8082:80
    networks:
      - bonusx-network
    depends_on:
      - database
    command: sh -c "npx knex migrate:latest && npx knex seed:run && npx nest start --debug --watch"

networks:
  bonusx-network:
    name: bonusx-network

volumes:
  pgdata:
